[server]
enableCORS = false
maxMessageSize = 200
maxUploadSize = 200
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[runner]
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"